sudo: required

language: bash
services: docker

env:
  - DOCKER_IMAGE=ffmpeg-pipe

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t ${DOCKER_IMAGE} .
  - docker images
  - docker tag ${DOCKER_IMAGE} $DOCKER_USERNAME/${DOCKER_IMAGE}
  - docker push $DOCKER_USERNAME/${DOCKER_IMAGE}
